name: ai_tutor_kazakhstan
description: AI Репетитор для начальной школы Казахстана.
publish_to: none
version: 0.2.0+2
environment:
  sdk: ^3.13.5
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: 1.6.0
  uuid: 4.5.3
  intl: 0.20.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
flutter:
  uses-material-design: true
  generate: true
  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans-Regular.ttf
        - asset: assets/fonts/NotoSans-Bold.ttf
          weight: 700
